### ISSUE TITLE
python-stix-v1.1.* isn't backward-compatible with earlier versions of STIX (ie, 1.0)

### ISSUE THREAD

**Issue by treyka** [STIXProject/python-stix#124]
Shy of bundling multiple releases of python-stix with my application and iteratively loading  them in reverse chronological order via try/except blocks (the "Hail Mary" of dependency management) what do y'all suggest?

**Comment by sarus** [comment]
Just started looking at STIX parsing and came across this thread.  Was quite concerned by this comment:

```
STIX v1.1.1 included some changes that were not backwards compatible with STIX v1.1
```

The versioning scheme being used by the project suggests the use of semantic versioning but is not following the semver conventions:

http://semver.org/

Namely backwards compatibility must be maintained across patch version (i.e., v1.1.0 -> v1.1.1).  In fact, in semver backwards compatibility must be maintained across the same major version.  Have you given any thought to adopting semver to prevent this type of confusion in the future?  

Apologies if you've already moved in this direction.  I'm still very new to this project.  Thanks!

**Comment by bworrell** [comment]
Hi @sarus! Thanks for the comment! The STIX language defines it's versioning policy here: https://stix.mitre.org/language/versioning_policy.html which is a quite a bit different than semantic versioning (as you noticed, heh). Check it out if you get a chance.

Several of our utilities and APIs follow semver (e.g., [stix-ramrod](https://github.com/STIXProject/stix-ramrod#versioning)). The data model APIs (python-stix/python-cybox/python-maec) orient themselves around the version of the language, which is definitely confusing at times because it tries to reconcile software versioning with the parent language/schema versioning, though the two aren't always super compatible :-\

Let us know if you have any thoughts on how to apply semantic versioning (or other versioning scheme) concepts to the STIX language! I also encourage you to bring these ideas up on our discussion lists :)

**Comment by guitarmanvt** [comment]
I agree with @sarus: the versioning difference between STIX and [semver.org](http://semver.org) is jarring. However, keeping **python-stix** in lock-step with the STIX version is probably less confusing overall than trying to maintain two separate versioning schemes.

That said, consider this potential solution:
1. **python-stix** version numbers remain in lock-step with STIX version numbers.
2. A separate project implements a "wrapper" around multiple versions of **python-stix**, insulating projects against newer STIX library explosions on data that worked fine with older STIX libraries. This new project would use semantic versioning ala  [semver.org](http://semver.org).

I thought about suggesting that the "sweet wrapper" project be named **pixy-stix** (https://en.wikipedia.org/wiki/Pixy_Stix). Unfortunately, **pixy** is already taken (http://www.cmucam.org/projects/cmucam5/wiki).

**Comment by gtback** [comment]
We currently maintain two branches of python-stix (1.1.1.x and 1.2.0.x). There's also a separate library (stix121) for STIX 1.2.1 that we don't maintain because I don't know of anyone using it (if I'm wrong, please let me know and we can update it). 

I would support a wrapper that supports Semantic Versioning, and would be happy to communicate with anyone who develops one to notify when there are breaking changes in this library. 

@wagner-certat as far as STIX itself is concerned, STIX 1 to STIX 2 was obviously a breaking change (XML to JSON, among many other changes), and caused the creation of a [new library](https://github.com/oasis-open/cti-python-stix2). The changes from STIX 2.0 to STIX 2.1 aren't likely to be backwards-compatible (or forwards-compatible), but that is up to the [OASIS Cyber Threat Intelligence Technical Committee](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=cti#feedback) that is developing STIX 2.
