### ISSUE TITLE
CIQ Identity type seems incomplete for names

### ISSUE THREAD

**Issue by johnwunder** [STIXProject/python-stix#187]
Our example content uses `PartyName/PersonName` and `PartyName/OrganisationName` for names, but the API only seems to support the more generic `PartyName/NameElement`.

The API should support the more specific types to correspond with our suggested practices.

**Comment by bworrell** [comment]
This was implemented though I'm not sure when. The example [here](https://github.com/STIXProject/python-stix/blob/master/examples/ciq_identity.py#L41) makes use of `OrganisationName` and `PersonName`.

The `PartyName` section of the generated XML looks like this:
```xml
 <xpil:PartyName xmlns:xpil="urn:oasis:names:tc:ciq:xpil:3">
    <xnl:NameLine xmlns:xnl="urn:oasis:names:tc:ciq:xnl:3">Foo</xnl:NameLine>
    <xnl:NameLine xmlns:xnl="urn:oasis:names:tc:ciq:xnl:3">Bar</xnl:NameLine>
    <xnl:PersonName xmlns:xnl="urn:oasis:names:tc:ciq:xnl:3">
      <xnl:NameElement>John Smith</xnl:NameElement>
    </xnl:PersonName>
    <xnl:PersonName xmlns:xnl="urn:oasis:names:tc:ciq:xnl:3">
      <xnl:NameElement>Jill Smith</xnl:NameElement>
    </xnl:PersonName>
    <xnl:OrganisationName xmlns:xnl="urn:oasis:names:tc:ciq:xnl:3">
      <xnl:NameElement>Foo Inc.</xnl:NameElement>
    </xnl:OrganisationName>
    <xnl:OrganisationName xmlns:xnl="urn:oasis:names:tc:ciq:xnl:3">
      <xnl:NameElement>Bar Corp.</xnl:NameElement>
    </xnl:OrganisationName>
  </xpil:PartyName>
```

I am going to close this out since I believe it has been resolved. @johnwunder, let me know if I missed something and I'll reopen!
