### ISSUE TITLE
Allow the STIXPackage constructor to accept a list of Observable objects in addition to an Observables object

### ISSUE THREAD

**Issue by gtback** [STIXProject/python-stix#23]
Currently, the constructor signature looks like this

``` python
def __init__(self, id_=None, idref_=None, 
             stix_header=None, indicators=None, observables=None):
```

However, `indicators` is supposed to be a native Python list of `stix.indicator.Indicator` objects, while `observables` should be a `cybox.core.Observables` object (which itself contains a list of `cybox.core.Observable` objects).

These should be made consistent, with `observables` also accepting a list. To prevent breaking existing code, the current functionality should also be kept.

**Comment by emmanvg** [comment]
After the TypedField changes we can no longer provide native lists of objects to initialize a STIXPackage like the example with `Indicator` shown here. We can support it by doing a `Indicators([Indicator(), ...,])` inside, but the convenience of having that inside the constructor as opposed to just passing a `Indicators` object is trivial. Any thoughts @gtback ? I think we could close this otherwise.

**Comment by gtback** [comment]
I would like to think this is still possible (maybe through creative use of the` Observables.__init__`), but since no one has really expressed a need for this in 4+ years, I'm fine just closing this.
