### ISSUE TITLE
attributeerror: module object has no attribute NS_LIST

### ISSUE THREAD

**Issue by kiko441500** [STIXProject/python-stix#291]
Hi

I have installed stix from  pip. And there is no mistake in the process of installing. But when I test the installing result and typed the command "import stix", The shell window reminded me that "attributeerror: module object has no attribute NS_LIST"

My installing environment is win7.

Is there someone can help me ? I have been confused for a week!!!
Uploading 
![qq 20160524134319](https://cloud.githubusercontent.com/assets/4480771/15493303/c30787bc-21b5-11e6-91ae-c4073587c193.png)

**Comment by gtback** [comment]
Hi @kiko441500. Are you installing from PyPI or from the GitHub repository? The GitHub repository is probably not in a great state to be installing from (but hopefully will be in the coming weeks).  I can't tell entirely from the screenshot you posted, but it looks like you're using the development version of CybOX (2.1.0.13.dev0).

**Comment by JennyQQQ** [comment]
Hi- I'm getting the same error, though i'm using python setup.py install.  The installation process itself seemed to have no errors, but when i try the test, >>>import stix,  I'm getting:  "AttributeError: 'module' object has no attribute 'NS_LIST'.  Below is the screenshot of the error, i also have saved the output of the install 

Here is a screenshot of the error:  
![import stix error](https://cloud.githubusercontent.com/assets/20729557/17259426/623a459c-5599-11e6-9f67-a6b2f4a1e29f.png)

**Comment by gtback** [comment]
Hi @JennyQQQ ! If you can, try uninstalling cybox (`pip uninstall cybox`) and then install the latest stable version (`pip install "cybox==2.1.0.12"`). If that doesn't fix it, also try uninstalling then re-installing stix as well.

I think this is caused because older versions of pip don't see the latest "development" release of cybox (2.1.0.13.dev1) as a "pre-release", and so install it when stix requires `cybox < 2.1.1.0`

Just to confirm my expectation, can you paste the output of `pip list` (especially any lines that include cybox, stix, mixbox, maec, or lxml)?

**Comment by kiko441500** [comment]
I have solve the problem. It is the problem of the version of Python. You could find the Intel python.

发自我的 iPhone

**Comment by JennyQQQ** [comment]
Greg, you're the man!  Thanks so much.  all it took was uninstalling cybox and reinstalling a newer version of cybox.  What is mysterious to me is that i used the exact same downloads as i did last time (the time that did work) - why it didnt work this time i'm not sure.  But your solution did.  

Thanks again!!! :) 
Jenny

here's the result of pip list:
cybox(2.1.0.12)
lxml (3.4.0)
maec (4.1.0.12)
mixbox (0.0.13)
ordered-set (2.0.1)
pip (8.1.2)
python-dateutil (2.5.3)
setuptools (16.0)six (1.10.0)
stix (1.1.1.5)
weakrefmethod (1.0.3)
xlrd (0.9.3)
xlrd (0.9.3)

**Comment by gtback** [comment]
Glad this is fixed, @kiko441500 and @JennyQQQ !

The reason this might have worked before, but failed recently, is that we have pushed new "pre-release" versions of CybOX (such as 2.1.0.13.dev1) . Newer versions of pip will (correctly) ignore these versions, but some older versions of pip will install them instead of the latest stable version (2.1.0.12).
