### ISSUE TITLE
Big STIX Indicator XML File with all Observables

### ISSUE THREAD

**Issue by valerianrossigneux** [STIXProject/python-stix#299]
Hi, do you happen to have a giant STIX Indicator XML file with all the Observable. I'd like to test out one of my program but I'm lacking input data.

**Comment by gtback** [comment]
Hi @valerianrossigneux. See [here](http://stixproject.github.io/about/#where-can-i-find-examples-of-stix-data-are-there-any-stix-repositories). You might also have some luck asking the [cti-users mailing list](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=cti#feedback).

I'm going to close this issue since it's not specific to the code in this repository, but feel free to ask any other questions you might have.
