### ISSUE TITLE
CIQ objects do not seem to be handled correctly in 1.2.0.1

### ISSUE THREAD

**Issue by rpiazza** [STIXProject/python-stix#302]
When I updated to 1.2.0.1, the CIQ details in the Identity object were missing.

**Comment by gtback** [comment]
Hey, @rpiazza, what are you using as an input file? Can you share a small snippet of code that demonstrates the issue? I'm assuming this was working in 1.2.0.0? It's possible with the transition to mixbox that the way extensions work got changed.

**Comment by rpiazza** [comment]
Try the idiom "identifying a threat actor group". The file name might be slightly different.

**Comment by clenk** [comment]
This is related to STIXProject/stixproject.github.io#331 and the idiom files @rpiazza mentioned are here: https://github.com/STIXProject/stixproject.github.io/tree/issue331/documentation/idioms/identity-group. It seems that when the <Identity> element is parsed, it isn't looking at the xsi:type attribute to know to create a CIQIdentity3_0Instance() instead of Identity().
