### ISSUE TITLE
AISMarking Structure Not Implemented

### ISSUE THREAD

**Issue by gleblanc1783** [STIXProject/python-stix#310]
I am working on Parsing TAXII messages with the STIX Package (I've tried 1.1.1.6 and 1.1.1.7) and I am receiving the following exception:

`NotImplementedError: Marking structure type not implemented AISMarkingStructure`

I can confirm that the AISMarkingStructure is in the etensions/marking/ais.py file:

```
$ egrep -r -nw "AIS:AISMarkingStructure" lib/
lib/python2.7/site-packages/stix/test/extensions/marking/ais.py:18:        'xsi:type': 'AIS:AISMarkingStructure'
lib/python2.7/site-packages/stix/test/extensions/marking/ais.py:31:        'xsi:type': 'AIS:AISMarkingStructure'
lib/python2.7/site-packages/stix/extensions/marking/ais.py:304:    _XSI_TYPE = "AIS:AISMarkingStructure"
```

I have cleared the pip cache and recreated my virtualenv thinking it may have been a cacheing error.

Here's the Python Code that's creating the document:

```
...
from stix.core import STIXPackage
#Using XML dump from test TAXII Message. Below command created the testAIS.taxii file
#print taxii_message.content_blocks[0].content
stix_package = STIXPackage.from_xml('/tmp/testAIS.taxii')
```

And the exception:

```
File "local/lib/python2.7/site-packages/stix/bindings/data_marking.py", line 352, in buildChildren
    raise NotImplementedError('Marking structure type not implemented ' + typeinfo.typename)
NotImplementedError: Marking structure type not implemented AISMarkingStructure
```

**Comment by gtback** [comment]
Hi, @gleblanc1783!

Did you `import stix.extensions.marking.ais` first? Unlike the other marking extensions, we don't automatically load AIS markings, since they aren't a published part of the STIX specification. We included them in this library since they're common enough that it's not worth a separate package for.

**Comment by gleblanc1783** [comment]
Nope I didn't!! Thank you so much, I will try this later/tomorrow.

By any chance, do you know if this was mentioned in the documentation **somewhere?** [either AIS or STIX]. I swear I read, re-read, googled and tried everything but I couldn't find that.

**Comment by packet-rat** [comment]
Gregory,
Well thanks to you we have it documented now 👍
Thanks Mate!


Patrick Maroney


On Nov 1, 2016, at 5:54 PM, Gregory LeBlanc <notifications@github.com> wrote:

Nope I didn't!! Thank you so much, I will try this later/tomorrow.

By any chance, do you know if this was mentioned in the documentation somewhere? [either AIS or STIX]. I swear I read, re-read, googled and tried everything but I couldn't find that.

**Comment by gleblanc1783** [comment]
That worked great. Thank you! I will close this issue. 

I wouldn't mind updating documentation with a mention to this, just point me in the right direction. Or - like Pat said, we can leave it as a closed issue for those who need to search.

**Comment by gtback** [comment]
@gleblanc1783, nope it's not in the documentation anywhere 🙁 . But it should be!

Since AIS is only supported in 1.1.1.x versions for now, it might be confusing if we put it into the [default documentation](https://stix.readthedocs.io/en/stable/) which is for STIX 1.2. That said, I don't necessarily think people will go into the 1.1.1.7 documentation looking for AIS help. If anyone has suggestions, I'm happy to implement them.

**Comment by brlogan** [comment]
Hey @gtback, do you guys intend to implement the AIS marking extension in 1.2.x?

**Comment by gtback** [comment]
@brlogan: What are you trying to do with the AIS extension in 1.2? I believe that DHS only accepts 1.1.1 content for AIS, so (as I understand it), there's not much you can do with AIS-marked 1.2 content. It's not too much work to add it (I don't think), but don't want to confuse people by supporting AIS in 1.2.

I'll mention @emmanvg so he sees this conversation.

**Comment by brlogan** [comment]
@gtback: Well, I wanted to upgrade to 1.2 so I could support 1.2 content. The idea was that my DHS content would be converted to 1.2 using Ramrod, but it fails because I get the "NotImplementedError" for AIS.

**Comment by gtback** [comment]
Ahh, that makes sense. I'm wondering whether it makes sense to have ramrod strip out the AIS markings. Or, if you need the AIS marking data in 1.2, we can add support for AIS in 1.2.0.x.

I hadn't thought about the "consuming AIS content" angle as much as trying to prevent people from *creating* 1.2 content with AIS markings.

**Comment by brlogan** [comment]
If my goal is to be able to consume AIS data, I think I'd want to keep the AIS markings so I can consume that piece as well. Plus, if DHS does decide to move to 1.2, it would be good to have it in there.

**Comment by gtback** [comment]
I expect at this point DHS is more likely to move to STIX 2.0 than 1.2, but your point about wanting to consume AIS content in python-stix 1.2.0.x makes a lot of sense. I need to think more about this, but I think it's reasonable for us to add some level of AIS support in the 1.2 branch.

**Comment by brlogan** [comment]
Sounds great! :)

**Comment by mikenerone** [comment]
May I ask when we'll see this released? My project has need of it, as well.

**Comment by gtback** [comment]
@mikenerone I'll try to get a release out this week.

**Comment by gtback** [comment]
I released python-stix 1.2.0.3 last night.

**Comment by TheDr1ver** [comment]
Did the documentation ever get updated for how to "officially" implement this extension? I just spent the last week or so figuring out how to get ISA Marking Structures working properly for consumption after we were getting them delivered via AIS, and I wanted to make sure there wasn't something I was missing (or an easier way to implement custom marking structures).

Basically, I used /stix/extensions/marking/ais.py and /stix/bindings/extensions/marking/ais.py as a framework to piece together my own .py extension files based off of the data I found here https://github.com/anl-cyberscience/FlexTransform/tree/master/ISAMarkingExtension 

Then I added `import stix.extensions.marking.isamarkings` to /stix/core/stix_package.py and /stix/data_marking.py (inside the entity_class function), and everything seems to be working.

Again, this felt really "dirty" just to be able to properly consume STIX files that used these markings without getting a NotImplemented error, so I just wanted to make sure this is how I was supposed to go about it, rather than an easier way.

**Comment by gtback** [comment]
AIS Markings are different than ISA Markings. You're saying you're getting ISA Markings via AIS? 

Besides the Argonne implementation, we are working to release our implementation of AIS markings, which would work similar to how AIS markings work (though part of a separate library).

**Comment by TheDr1ver** [comment]
Correct - I'm saying through the AIS system, a large number of STIX files that we were receiving used ISA Markings. The only way I was able to get python-stix to read them without throwing NotImplementedError and crashing was to make a custom extension through the process I mentioned. 

I just wanted to make sure that the process I went through was correct, and, if not, what the recommended process would be for consuming custom markings (like the ISA ones)... Because I feel like had I not found that old FlexTransform repo with most of the work done already I would have pretty much been dead in the water when it came to consuming STIX files with ISA Markings.

**Comment by brlogan** [comment]
I can confirm that I have also seen the ISAMarkingsType referenced in STIX from AIS.

**Comment by gtback** [comment]
_Just FYI for anyone who reads this thread later: The last several comments are mostly unrelated to this GitHub issue, which is talking about the AIS Marking structure._

Ok, thanks @TheDr1ver and @brlogan. 

I think it would be wrong for python-stix to silently ignore data markings it doesn't understand (at least by default). There's not a ton of documentation on implementing custom marking extensions, other than looking at existing markings and adapting them. What you've done with what's in the FlexTransform repo is essentially the right approach. 

As I mentioned, we also have an implementation of ISA markings, explicitly designed to work with python-stix, that we are going through the process for getting approval to release.
