### ISSUE TITLE
Get the id_ of an object

### ISSUE THREAD

**Issue by dilyanpalauzov** [STIXProject/python-stix#323]
In the example below, how can I get the id_ of the address_object (except iterating over all p.observables and filtering them)

```
import stix.core
import cybox.objects.address_object

p = stix.core.STIXPackage()
a = cybox.objects.address_object.Address("1.2.3.4")
p.add_observable(a)
#how to get the id_ of a?
print(p.to_xml())
```

**Comment by dilyanpalauzov** [comment]
This works with
```p.observables[-1].id_```

**Comment by gtback** [comment]
Yes, so part of the issue is that there is an `Object` layer between the `Observable` and the "ObjectProperties" (in this case, the IPv4 `Address` object). Only `Observable` and `Object` have IDs. 

You can get the ID of the `Observable` with:
```
p.observables[0].id_
```

To get the ID of the `Object` holding the `Address`:
```
p.observables[0].object_.id_
a.parent.id_
```

The latter is a shortcut, not defined by the CybOX/STIX specs, but useful for cases like this.
